name: JaimePortfolio
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn
  - xgboost
  - lightgbm
  - plotly
  - missingno
  - shap
  - pip
  - pip:
      - kagglehub
      - lime
      - streamlit
      - gradio
